# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Cache-Memcached-Managed
version:      0.19
version_from: lib/Cache/Memcached/Managed.pm
installdirs:  site
requires:
    Cache::Memcached:              0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
