--- #YAML:1.0
name:               Cache-Memcached-Managed
version:            0.21
abstract:           provide API for managing cached information
author:
    - Elizabeth Mattijsen (liz@dijkmat.nl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::Memcached:  0
    Scalar::Util:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
